name: HTTP Request

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**/*'
  # You can customize the triggers based on your requirements, like pull_request or schedule.

jobs:
  hit_url:
    runs-on: ubuntu-latest

    steps:
      - name: HTTP Request
        run: curl -X GET ${{ secrets.RENDER_DEPLYOMENT_URL }}
        # Replace the URL with the desired URL you want to hit
